### Get all products
GET localhost:8082/products

### Customer with number
GET localhost:8082/products/12

### Post a product
POST localhost:8082/products
Content-Type: application/json

{
  "name": "Mangos",
  "price": 2.79
}

### Put a product
PUT localhost:8082/products/19
Content-Type: application/json

{
  "name": "aaa",
  "price": 2.79
}

### Delete a product
DELETE localhost:8082/products/19

--------------------

